### ISSUE TITLE
Does this support nesting

### ISSUE THREAD

**Issue by xqgdmg** [geekmouse/FleX2Json#1]
Excuse me, do you support nesting JSON in JSON? I look forward to your reply. Thank you

**Comment by dprat0821** [comment]
> Excuse me, do you support nesting JSON in JSON? I look forward to your reply. Thank you

Support 3-layers JSON structure. However, in the current version, only the array of basic types is supported in the 3rd layer. Please check out column G-J in [THIS SHEET ](https://github.com/geekmouse/FleX2Json/blob/master/sample/SampleData.xlsx) for example
